pipeline {
    agent any

    stages {
        stage('Unit Test - Backend') {
            // agent{
            //     docker {                              //pulling a docker instance with everything needed to run the tests
            //         image 'snakee/golang-junit:1.21' //it can be repleaced by a jenkins plugin tho
            //         reuseNode true
            //     }
            // }
            steps {
                dir('bugtracker-backend'){
                    sh 'go test -v ./...'
                }
            }
        }
    }
}