pipeline {
    agent any

    tools { 
        go '1.26.2'
      //  nodejs 'NodeJS' //it has to coincide with the Name in tool config 
    } //it has to coincide with the plugin installed version 

    stages {
        stage('Unit Test - Backend') {
            // agent{
            //     docker {                              //pulling a docker instance with everything needed to run the tests
            //         image 'snakee/golang-junit:1.21' //it can be repleaced by a jenkins plugin tho
            //         reuseNode true
            //     }
            // }
            steps {
                dir('bugtracker-backend'){
                    sh 'go test -v ./...'
                }
            }
        // }
        stage('Unit Test - Frontend'){
            agent { 
                docker { 
                    image 'node:18-alpine' 
                    reuseNode true    
                } 

            }
            steps{
                dir('bugtracker-frontend'){
                    sh '''
                        npm ci 
                        npm test
                    '''
                }
            }
            post{
                always{
                    junit 'bugtracker-frontend/test-result.xml' //this is a way to do it, but need to run test locally, which doesn't makes sense for this implementation
                }
            }
        }
    }

}